
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sentinel
  namespace: sentinel
  labels:
    app: sentinel
spec:
  selector:
    matchLabels:
      app: sentinel
  template:
    metadata:
      labels:
        app: sentinel
    spec:
      serviceAccountName: sentinel
      containers:
      - name: sentinel
        image: ghcr.io/flying-lama/sentinel:latest
        env:
        - name: SENTINEL_ORCHESTRATION_TYPE
          value: "kubernetes"
        - name: SENTINEL_DOMAIN
          value: "example.com"
        - name: SENTINEL_RECORD
          value: "lb"
        - name: SENTINEL_LOG_LEVEL
          value: "INFO"
        - name: SENTINEL_INWX_RECORD_ID
          value: "1111"
        - name: SENTINEL_INWX_USER
          valueFrom:
            secretKeyRef:
              name: sentinel-inwx-credentials
              key: username
        - name: SENTINEL_INWX_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sentinel-inwx-credentials
              key: password
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
